const agentNames = ["Research Coordinator Agent", "Literature Retrieval Agent", "PDF Understanding Agent", "Semantic Analysis Agent", "Knowledge Graph Agent", "Citation Network Agent", "Novelty Assessment Agent", "Research Gap Agent", "Proposal Generation Agent", "Hallucination Verification Agent"];
const agents = document.querySelector('#agents'), template = document.querySelector('#agent');
agentNames.forEach((name, i) => { const el = template.content.cloneNode(true); const card = el.querySelector('.agent'); card.dataset.index = i; el.querySelector('span').textContent = name; agents.append(el); });
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const queryInput = document.querySelector('#query');
function escape(text) { const box = document.createElement('span'); box.textContent = text ?? ''; return box.innerHTML; }
function list(values) { return `<ul>${values.map(v => `<li>${escape(v)}</li>`).join('')}</ul>`; }
function downloadReport(report) { const blob = new Blob([JSON.stringify(report, null, 2)], {type:'application/json'}); const link = Object.assign(document.createElement('a'), {href:URL.createObjectURL(blob), download:'anveshak-research-report.json'}); link.click(); URL.revokeObjectURL(link.href); }
function speakReport(report) { const message = `Anveshak AI report. Novelty assessment: ${report.novelty_assessment.score} out of 100, ${report.novelty_assessment.interpretation}. ${report.research_gaps.candidate_gaps.slice(0, 2).join(' ')}`; if (!('speechSynthesis' in window)) return alert('Speech output is not supported by this browser.'); speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(message)); }
function saveQuery(query) { const prior = JSON.parse(localStorage.getItem('anveshak-recent-queries') || '[]'); localStorage.setItem('anveshak-recent-queries', JSON.stringify([query, ...prior.filter(item => item !== query)].slice(0, 5))); renderHistory(); }
function renderHistory() { const queries = JSON.parse(localStorage.getItem('anveshak-recent-queries') || '[]'); const area = document.querySelector('#history'); const listArea = document.querySelector('#recent-queries'); area.hidden = !queries.length; listArea.innerHTML = queries.map(q => `<button class="recent-query" data-query="${escape(q)}">${escape(q)}</button>`).join(''); listArea.querySelectorAll('button').forEach(button => button.addEventListener('click', () => { queryInput.value = button.dataset.query; queryInput.focus(); })); }
function sourceActions(paper) { const doi = paper.url ? `<a class="link-button" href="${escape(paper.url)}" target="_blank" rel="noreferrer">View source ↗</a>` : ''; const pdf = paper.pdf_url ? `<a class="link-button pdf" href="${escape(paper.pdf_url)}" target="_blank" rel="noreferrer">Download PDF ↓</a>` : ''; const search = `<a class="link-button" href="https://scholar.google.com/scholar?q=${encodeURIComponent(paper.title)}" target="_blank" rel="noreferrer">Find full text ↗</a>`; return `<div class="paper-actions">${doi}${pdf}${search}</div>`; }
function showReport(r) {
  const papers = r.papers.map(p => `<div class="paper"><a class="paper-title" href="${escape(p.url || '#')}" target="_blank" rel="noreferrer">${escape(p.title)}</a><small>${escape(p.authors)} · ${p.year || 'n.d.'} · ${escape(p.source)} · ${p.citations} citations</small>${sourceActions(p)}</div>`).join('');
  document.querySelector('#result').innerHTML = `<div class="report-head"><div><span class="eyebrow">Final explainable report</span><h2>${escape(r.plan.query)}</h2><p>Retrieved from ${escape(r.sources.join(', '))}. PDF buttons appear only when a source provides an open-access direct link.</p></div><div class="report-actions"><div class="score">Verification confidence<br><strong>${Math.round(r.verification.overall_confidence * 100)}%</strong></div><button class="outline-button" id="read-report">🔊 Read summary</button><button class="outline-button" id="download-report">⇩ Export JSON</button></div></div><div class="grid"><article class="card sources"><h3>Retrieved literature</h3>${papers}</article><article class="card"><h3>Semantic themes</h3>${r.semantic_analysis.themes.map(t => `<span class="tag">${escape(t.name)} · ${t.mentions}</span>`).join('')}<h3>Novelty screen</h3><p><b>${r.novelty_assessment.score}/100 — ${escape(r.novelty_assessment.interpretation)}</b></p><p>${escape(r.novelty_assessment.caveat)}</p></article><article class="card"><h3>Candidate research gaps</h3>${list(r.research_gaps.candidate_gaps)}<p>${escape(r.research_gaps.warning)}</p></article><article class="card"><h3>Proposal outline</h3><p><b>${escape(r.proposal.title)}</b></p><p>${escape(r.proposal.objective)}</p><p><b>Method:</b> ${escape(r.proposal.methodology)}</p></article><article class="card"><h3>Verification ledger</h3>${r.verification.checks.map(c => `<p><b>${Math.round(c.confidence * 100)}%</b> ${escape(c.claim)}<br><small>Evidence: ${escape(c.evidence.join('; '))}</small></p>`).join('')}</article><article class="card"><h3>Knowledge graph</h3><p>${r.knowledge_graph.nodes.length} nodes and ${r.knowledge_graph.links.length} evidence relationships were generated.</p><h3>Most cited in this result set</h3>${list(r.citation_network.most_influential.map(p => `${p.title} (${p.citations})`))}</article></div>`;
  document.querySelector('#download-report').addEventListener('click', () => downloadReport(r)); document.querySelector('#read-report').addEventListener('click', () => speakReport(r)); document.querySelector('#result').hidden = false; document.querySelector('#result').scrollIntoView({behavior:'smooth'});
}
function setupVoice() { const status = document.querySelector('#voice-status'); const button = document.querySelector('#voice-input'); const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) { button.disabled = true; status.textContent = 'Voice input is unavailable in this browser. You can still type your question.'; return; } const recognition = new Recognition(); recognition.lang = 'en-IN'; recognition.interimResults = true; recognition.onstart = () => { button.classList.add('listening'); status.textContent = 'Listening… speak your research question.'; }; recognition.onresult = event => { queryInput.value = [...event.results].map(result => result[0].transcript).join(''); }; recognition.onerror = () => { status.textContent = 'Voice input could not start. Please try again or type your question.'; }; recognition.onend = () => { button.classList.remove('listening'); if (!status.textContent.includes('could not')) status.textContent = 'Voice input complete. Review the question, then run the pipeline.'; }; button.addEventListener('click', () => recognition.start()); }
document.querySelector('#research-form').addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('.controls button'); const query = queryInput.value.trim(); button.disabled = true; button.textContent = 'Coordinating agents…'; document.querySelector('#result').hidden = true; const cards = [...document.querySelectorAll('.agent')]; cards.forEach(c => { c.className = 'agent'; c.querySelector('small').textContent = 'Waiting'; });
  try { const request = fetch('/api/research', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({query, domains:[document.querySelector('#domain').value]})}); for (const card of cards) { card.classList.add('running'); card.querySelector('small').textContent = 'Working'; await sleep(170); card.classList.replace('running','done'); card.querySelector('small').textContent = 'Completed'; } const response = await request; if (!response.ok) throw new Error(await response.text()); const report = await response.json(); saveQuery(query); showReport(report); } catch (error) { alert(`Unable to complete the research run: ${error.message}`); } finally { button.disabled = false; button.innerHTML = 'Run research pipeline <span>→</span>'; } });
setupVoice(); renderHistory();
