const agentNames = ["Research Coordinator Agent", "Literature Retrieval Agent", "PDF Understanding Agent", "Semantic Analysis Agent", "Knowledge Graph Agent", "Citation Network Agent", "Novelty Assessment Agent", "Research Gap Agent", "Proposal Generation Agent", "Hallucination Verification Agent"];
const agents = document.querySelector('#agents'), template = document.querySelector('#agent');
agentNames.forEach((name, i) => { const el = template.content.cloneNode(true); const card = el.querySelector('.agent'); card.dataset.index = i; el.querySelector('span').textContent = name; agents.append(el); });
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
function escape(text) { const box = document.createElement('span'); box.textContent = text ?? ''; return box.innerHTML; }
function list(values) { return `<ul>${values.map(v => `<li>${escape(v)}</li>`).join('')}</ul>`; }
function showReport(r) {
  const papers = r.papers.map(p => `<div class="paper"><a href="${escape(p.url || '#')}" target="_blank" rel="noreferrer">${escape(p.title)}</a><small>${escape(p.authors)} · ${p.year || 'n.d.'} · ${escape(p.source)} · ${p.citations} citations</small></div>`).join('');
  document.querySelector('#result').innerHTML = `<div class="report-head"><div><span class="eyebrow">Final explainable report</span><h2>${escape(r.plan.query)}</h2><p>Sources: ${escape(r.sources.join(', '))}</p></div><div class="score">Verification confidence<br><strong>${Math.round(r.verification.overall_confidence * 100)}%</strong></div></div><div class="grid"><article class="card"><h3>Retrieved literature</h3>${papers}</article><article class="card"><h3>Semantic themes</h3>${r.semantic_analysis.themes.map(t => `<span class="tag">${escape(t.name)} · ${t.mentions}</span>`).join('')}<h3>Novelty screen</h3><p><b>${r.novelty_assessment.score}/100 — ${escape(r.novelty_assessment.interpretation)}</b></p><p>${escape(r.novelty_assessment.caveat)}</p></article><article class="card"><h3>Candidate research gaps</h3>${list(r.research_gaps.candidate_gaps)}<p>${escape(r.research_gaps.warning)}</p></article><article class="card"><h3>Proposal outline</h3><p><b>${escape(r.proposal.title)}</b></p><p>${escape(r.proposal.objective)}</p><p><b>Method:</b> ${escape(r.proposal.methodology)}</p></article><article class="card"><h3>Verification ledger</h3>${r.verification.checks.map(c => `<p><b>${Math.round(c.confidence * 100)}%</b> ${escape(c.claim)}<br><small>Evidence: ${escape(c.evidence.join('; '))}</small></p>`).join('')}</article><article class="card"><h3>Knowledge graph</h3><p>${r.knowledge_graph.nodes.length} nodes and ${r.knowledge_graph.links.length} evidence relationships were generated. Graph visual rendering is the next extension point.</p><h3>Most cited in this result set</h3>${list(r.citation_network.most_influential.map(p => `${p.title} (${p.citations})`))}</article></div>`;
  document.querySelector('#result').hidden = false; document.querySelector('#result').scrollIntoView({behavior:'smooth'});
}
document.querySelector('#research-form').addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('button'); button.disabled = true; button.textContent = 'Coordinating agents…'; document.querySelector('#result').hidden = true; const cards = [...document.querySelectorAll('.agent')]; cards.forEach(c => { c.className = 'agent'; c.querySelector('small').textContent = 'Waiting'; });
  try { const request = fetch('/api/research', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({query:document.querySelector('#query').value, domains:[document.querySelector('#domain').value]})}); for (const card of cards) { card.classList.add('running'); card.querySelector('small').textContent = 'Working'; await sleep(170); card.classList.replace('running','done'); card.querySelector('small').textContent = 'Completed'; } const response = await request; if (!response.ok) throw new Error(await response.text()); showReport(await response.json()); } catch (error) { alert(`Unable to complete the research run: ${error.message}`); } finally { button.disabled = false; button.innerHTML = 'Run research pipeline <span>→</span>'; } });
